version: "3.9"

volumes:
   mysql:      
   redis: 

services:

  chatty:
    build: .
    restart: always
    depends_on:
      - "db"
      - "redis"
      - "elasticsearch"
    volumes:
      - ".:/chatty"
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql:/var/lib/mysql 
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  redis:
    image: redis
    volumes:
        - "redis:/data" 
    restart: always
    environment:
      REDIS_HOST: redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:6.8.4
    restart: always
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    ports:
      - "9200:9200"

  sidekiq:
    build: .
    depends_on:
      - "db"
      - "redis"
      - "elasticsearch"
      - "chatty"

    command: bundle exec sidekiq -C config/sidekiq.yml  | tee log/sidekiq.log
    restart: unless-stopped
    volumes:
      - ".:/chatty"
   